version: "3"

services:
  jenkins:
    build:   .
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./jenkins_home:/var/jenkins_home"  # previously created with correct permissions

    ports:
      - '8080:8080'
      - '50000:50000'
      - '8090:8090'

